# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'POC_WebView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for POC_WebView
  pod "ESPullToRefresh"

  target 'POC_WebViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'POC_WebViewUITests' do
    # Pods for testing
  end

end
